#+title: 柯萬里 -- 履歷 -- \minguodate{}
#+author: 柯萬里
#+setupfile: resume-setup-zh-tw
#+export_file_name: /home/ilmari/my-files/websites/ilmarikoria/ilmari-koria-resume-zh-tw

* =xelatex-export=                                                                                  :noexport:
#+begin_src elisp
(setq org-latex-pdf-process '(
"xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"
"bibtex %b"
"xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"
"xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"
))
#+end_src

* 柯萬里

#+begin_center
履歷（最新版）： \minguodate{} --- [[mailto:ilmarikoria@posteo.net][ilmarikoria@posteo.net]] --- [[https://uk.linkedin.com/in/ilmari-koria-3151a5291][LinkedIn]] 
#+end_center

** About
London-based X-standards content markup technologies professional and University of London graduate. Comprehensive spoken and written language competence and digital literacy, with concentration on free open-source tools and implementations. Proven communication skills, team working ability and leadership initiative in a range of administrative, service and volunteer roles.
** Experience
*** Bloomsbury Publishing Plc, Digital Development \hfill London 
- /Content Analyst/ \hfill Jul 2023 -- Present
  - Quality assurance (QA), testing and management of the platform’s XML content.
  - Checking XML coded texts against source editions for structural and textual errors.
  - Following automated and manual routines and checklists systematically in order to identify and rectify XML errors.
  - Inputting and checking any required metadata and taxonomy indexing to aid discoverability of XML texts.
  - Testing online content on Bloomsbury platforms to identify data/platform issues.
  - Analysing content and contributing to mark-up guidelines.
  - Managing the workflow from conversion to upload for content sets on existing platforms.
** Education
- 2022 \mytab *National Chengchi University*, Mandarin Language Course (nine months via scholarship) \hfill Taipei
- 2020 \mytab *King's College London*, Master of Arts in Digital Humanities \hfill London
- 2019 \mytab *SOAS University of London*, Postgraduate Diploma \hfill London 
- 2018 \mytab *University of Kent*, Bachelor of Arts with First Class Honours \hfill Canterbury
** Leadership
 - 2019 \mytab *Student Society Founder and President*, SOAS University of London \hfill London
 - 2018 \mytab *Student Peer Mentor* and *Student Ambassador*, University of Kent \hfill Canterbury
** Technical Training                                                                              :noexport:
- 2023 \mytab Crane Softwrights Ltd. /Practical Transformation Using XSLT and XPath/ (24 training hrs.) [certificate]
** Technical Tools
- *Markup*: XML, HTML, CSS, \LaTeX{} --- *Scripting and Querying*: Lisp, Python, XSL/XSLT, XPath, XQuery --- *Development*: GNU/Linux (Debian), Bash, PowerShell, OpenAI, BaseX, Git, oXygen, GNU Emacs, Atlassian (Jira, Trello).
** Language Proficiency
- *English*: Advanced --- *Finnish*: Advanced --- *Mandarin*: Professional competency --- *Cantonese*: Conversational.
