#+title: Ilmari Koria Résumé -- Updated {{{time(%b %e %Y)}}}
#+author: Ilmari Koria
#+setupfile: resume-setup
#+export_file_name: ilmari-koria-resume.pdf

* Ilmari Koria
@@latex:\pagestyle{fancy}@@

#+begin_center

Résumé \today{} --- [[mailto:ilmarikoria@posteo.net][ilmarikoria@posteo.net]] --- [[https://uk.linkedin.com/in/ilmari-koria-3151a5291][LinkedIn]] --- [[https://github.com/ilmari-koria/org-resume][GitHub]] --- @@latex:\chtex{華文姓名：}\ruby{\chtex{柯}}{Kē}\ruby{\chtex{萬}}{Wàn}\ruby{\chtex{里}}{lǐ}@@
#+end_center

** About
London-based X-standards content markup technologies professional and University of London graduate. Comprehensive spoken and written language competence and digital literacy, with concentration in free open-source tools and implementations. Proven communication skills, team working ability and leadership initiative in a range of administrative, service and volunteer roles.

** Experience
*** Bloomsbury Publishing Plc, Digital Development \hfill London
- /Content Analyst/ (XML) \hfill Jul 2023 -- Present
  - Quality assurance (QA), testing and management of platform XML content.
  - Checking XML coded texts against source editions for structural and textual errors.
  - Following automated and manual routines and checklists systematically in order to identify and rectify XML errors.
  - Inputting and checking any required metadata and taxonomy indexing to aid discoverability of XML texts.
  - Testing online content on Bloomsbury platforms to identify data/platform issues.
  - Analysing content and contributing to mark-up guidelines.
  - Managing workflow from conversion to upload for content sets on existing platforms.
** Education
- 2022 \mytab *National Chengchi University*, Mandarin Language Course (nine months via scholarship) \hfill Taipei
- 2020 \mytab *King's College London*, Master of Arts in Digital Humanities \hfill London
- 2019 \mytab *SOAS University of London*, Postgraduate Diploma \hfill London 
- 2018 \mytab *University of Kent*, Bachelor of Arts with First Class Honours \hfill Canterbury
** Leadership
 - 2019 \mytab *Student Society Founder and President*, SOAS University of London \hfill London
 - 2018 \mytab *Student Peer Mentor* and *Student Ambassador*, University of Kent \hfill Canterbury
** Technical Tools
- *XML:* XSL/XSLT, XPath, XQuery, Schematron, BaseX, oXygen --- *Markup & Scripting:* JSON, HTML, CSS, \LaTeX{}, Python, shell (Bash) --- *Development*: GNU/Linux (Debian), Git, GNU Emacs, Atlassian (Jira, Trello).
** Language Proficiency
- *English*: advanced --- *Finnish*: advanced --- *Mandarin:* high-intermediate --- *Cantonese*: conversational.







