#+title: Ilmari Koria Résumé -- Updated {{{time(%b %e %Y)}}}
#+author: Ilmari Koria
#+setupfile: resume-setup
#+export_file_name: ilmari-koria-resume.pdf

# ATS friendly formatting

* Ilmari Koria
@@latex:\pagestyle{fancy}@@

#+begin_center
Résumé: \today{} --- [[mailto:ilmarikoria@posteo.net][ilmarikoria@posteo.net]] --- London
#+end_center



** About
London-based X-standards content markup technologies professional and
University of London graduate. Comprehensive spoken and written
language competence and digital literacy, with concentration in free
open-source tools and implementations. Proven communication skills,
team working ability and leadership initiative delivering XML
data-driven solutions within academic publishing.

** Experience
# Basic structure as follows:
# - Soft skill + task/problem + hard skill solution = result.
# Percentage values are what the candidate estimates as the result or
# effect. The idea is to demonstrate how one `qualitatively` gauges ones
# impact in a numerical form. In this sense, they are not arbitrary.

*** Bloomsbury Publishing Plc, Digital Development, London
- /Content Analyst/ (XML), Jul 2023 -- Present
  - Quality assurance (QA), testing and management of platform XML content.
  - Checking XML coded texts against source editions for structural and textual errors.
  - Following automated and manual routines and checklists systematically in order to identify and rectify XML errors.
  - Inputting and checking any required metadata and taxonomy indexing to aid discoverability of XML texts.
  - Testing online content on Bloomsbury platforms to identify data/platform issues.
  - Analysing content and contributing to mark-up guidelines.
  - Managing workflow from conversion to upload for content sets on existing platforms.

** Education
- *National Chengchi University*, Three semesters of Mandarin language training, Taipei     
- *King's College London*, Master of Arts in Digital Humanities, London     
- *SOAS University of London*, Postgraduate Diploma, London     
- *University of Kent*, Bachelor of Arts with First Class Honours, Canterbury 

** Technical Training
#+latex: \bulletlist
- /Practical Transformation Using XSLT and XPath/, 2024, 24 hrs., Crane Softwrights Ltd. (Online course)
- /DHOxSS: Applied Data Analysis for the Humanities/, 2019, 25 hrs., University of Oxford        
- /Introduction to Python: Data Analysis and Programming/, 2019, 25 hrs., University of London        

** Tools and Language Skills
#+latex: \nobulletlist
- *XML:* XSLT, XQuery, Schematron, DocBook, TEI --- *Markup & Scripting:* HTML, CSS, \LaTeX{}, Bash, Batch/cmd.exe --- *Development:* BaseX (NoSQL), oXygen, GNU/Linux Debian, Git, GNU Emacs, Atlassian (Jira, Trello)            
- *Languages*: *English*: advanced --- *Finnish*: advanced --- *Mandarin:* high-intermediate --- *Cantonese*: basic. 



