#+title: Ilmari Koria Résumé -- Updated {{{time(%b %e %Y)}}}
#+author: Ilmari Koria
#+setupfile: resume-setup
#+export_file_name: ilmari-koria-resume.pdf

* Ilmari Koria
@@latex:\pagestyle{fancy}@@

#+begin_center
Résumé: \today{} --- [[mailto:ilmarikoria@posteo.net][ilmarikoria@posteo.net]] --- ~+44 (0) 77 462 75400~ --- London
#+end_center


** About
London-based X-standards content markup technologies professional and
University of London graduate. Comprehensive spoken and written
language competence and digital literacy, with concentration in free
open-source tools and implementations. Proven communication skills,
team working ability and leadership initiative delivering XML
data-based solutions within the publishing industry.

** Experience
# Basic structure as follows:
# - Soft skill + task/problem + hard skill solution = result.
# Percentage values are what the candidate estimates as the result or
# effect. The idea is to demonstrate how one `qualitatively` gauges ones
# impact in a numerical form. In this sense, they are not arbitrary.

*** Bloomsbury Publishing Plc, Digital Development \hfill London
- /Content Analyst/ (XML) \hfill Jul 2023 -- Present
  - Excellent communication skills demonstrated by liaising with
    sister team to automate XML editing process using XSLT and batch
    scripts, resulting in 5% efficiency increase in delivering
    (auto)-generated metadata to external stakeholders.
  - Proven teamwork skills demonstrated by regularly updating team
    Wiki with XQuery scripts to automate common XML data processes,
    leading to 5% increase in team-wide productivity.
  - Strong organisational skills evidenced by in-progress development
    of content architecture solution for MathML equation markup on
    company web platform, projected to increase platform accessibility
    by 5%.
  - Solid analytical skills demonstrated by consistently developing
    internal XML schema enhancements, resulting in 5% reduction in
    quality assurance testing time.
  - Effective problem-solving skills evidenced by applying BaseX XML
    editing knowledge for quality assurance testing and bug fixes,
    reducing spending on XML reworks by external vendors by 5%.
  - Good self-development skills demonstrated by 10 years of daily use
    of GNU/Linux Debian, and associated technologies, resulting in
    solid computing skills and the ability to efficiently learn new
    technical tools.

** Technical Tools and Language Skills
- *XML:* XSLT, XQuery, Schematron --- *Markup & Scripting:* HTML, CSS,
  \LaTeX{}, Bash, Batch/cmd.exe --- *Development*: BaseX
  (NoSQL), oXygen, GNU/Linux Debian, Git (and GitHub), GNU Emacs, Atlassian (Jira,
  Trello).
- *English*: advanced --- *Finnish*: advanced --- *Mandarin:*
  high-intermediate --- *Cantonese*: basic[fn:4].

** Technical Training
- 2024 \mytab [[https://www.udemy.com/certificate/UC-11294ef2-5e24-498a-8d7b-0eca9fe72b29/][Practical Transformation Using XSLT and XPath]], G. Ken
    Holman/Udemy \hfill Online course (\ul{24 hrs.})

** Education
- *National Chengchi University*[fn:1], Three semesters of Mandarin language training \hfill Taipei
- *King's College London*, Master of Arts in Digital Humanities \hfill London
- *SOAS University of London*[fn:2], Postgraduate Diploma \hfill London
- *University of Kent*[fn:3], Bachelor of Arts with First Class Honours \hfill Canterbury

* Footnotes                                                        :noexport:
[fn:4] Founder of `London Cantonese Language Meetup.'
[fn:3] Acted as Student Peer Mentor and Student Ambassador.
[fn:2] Acted as student society founder and president. 
[fn:1] Recipient of RoC Ministry of Education scholarship (9 months).

